- name: Configure Docker and Deploy Application on EC2
  hosts: all
  become: true
  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from DockerHub
      docker_image:
        name: bindukantharaju/banking-app
        tag: "{{ image_tag }}"
        source: pull

    - name: Run Docker container
      docker_container:
        name: banking-app
        image: "bindukantharaju/banking-app:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "8084:8081"

